/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotelmanagement;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author swapnil
 */
public class Employee1 extends javax.swing.JFrame {
    public int upck = 0;
    public String ID = "", stat = "";

    /**
     * Creates new form Employee1
     */
    public Employee1() {
        initComponents();
        retreve();
    }
    
    public void retreve()
    {
        DefaultTableModel dm = new employee_update().getData("n");
        
        jTable1.setModel(dm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        fn_jTextField5 = new javax.swing.JTextField();
        ln_jTextField7 = new javax.swing.JTextField();
        et_jTextField11 = new javax.swing.JTextField();
        ad_jTextField10 = new javax.swing.JTextField();
        pn_jTextField8 = new javax.swing.JTextField();
        sal_jTextField12 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("First Name");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(200, 90, 90, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Last Name");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(200, 130, 90, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Employee Type");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(200, 170, 110, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Address");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(200, 210, 110, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Phone");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(200, 250, 90, 40);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Salary");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(200, 300, 90, 30);
        jPanel1.add(fn_jTextField5);
        fn_jTextField5.setBounds(320, 90, 170, 30);

        ln_jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ln_jTextField7ActionPerformed(evt);
            }
        });
        jPanel1.add(ln_jTextField7);
        ln_jTextField7.setBounds(320, 130, 170, 30);
        jPanel1.add(et_jTextField11);
        et_jTextField11.setBounds(320, 170, 170, 30);
        jPanel1.add(ad_jTextField10);
        ad_jTextField10.setBounds(320, 220, 170, 30);
        jPanel1.add(pn_jTextField8);
        pn_jTextField8.setBounds(320, 260, 170, 30);
        jPanel1.add(sal_jTextField12);
        sal_jTextField12.setBounds(320, 300, 170, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(570, 90, 110, 40);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("REMOVE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(570, 140, 110, 40);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setText("UPDATE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(570, 190, 110, 40);

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton5.setText("BACK");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(30, 20, 90, 31);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(0, 430, 850, 310);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("EMPLOYEE");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(310, 0, 190, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotelmanagement/cover__WWW.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, -10, 850, 740);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 849, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 743, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ln_jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ln_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ln_jTextField7ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String FN = fn_jTextField5.getText();
        String LN = ln_jTextField7.getText();
        String ET = et_jTextField11.getText();
        String AD = ad_jTextField10.getText();
        String phone = pn_jTextField8.getText();
        String salary = sal_jTextField12.getText();
        if( new employee_update().add(FN,LN,ET,AD,phone,salary,"OFF DUTY"))
        {
            JOptionPane.showMessageDialog(null,"New Employee ADDED !! ");
            retreve();
        fn_jTextField5.setText("");
        ln_jTextField7.setText("");
        et_jTextField11.setText("");
        ad_jTextField10.setText("");
        pn_jTextField8.setText("");
        sal_jTextField12.setText("");
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Not ADDED !! ");
        }
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int index = jTable1.getSelectedRow();
        String id =jTable1.getValueAt(index,0).toString();
        if( new employee_update().delete(id) )
        {
            JOptionPane.showMessageDialog(null,"REMOVED !! ");
            retreve();
        }
        else 
        {
            JOptionPane.showMessageDialog(null,"NOT REMOVED !! ");
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        if( upck == 0 )
        {
            upck = 1;
            System.out.println("update hbe na ekhon");
            int index = jTable1.getSelectedRow();
            ID = jTable1.getValueAt(index,0).toString();
            String Fn =jTable1.getValueAt(index,1).toString();
            String LN =jTable1.getValueAt(index,2).toString();
            String ET =jTable1.getValueAt(index,3).toString();
            String AD =jTable1.getValueAt(index,4).toString();
            String phn =jTable1.getValueAt(index,5).toString();
            String sal =jTable1.getValueAt(index,6).toString();
            stat = jTable1.getValueAt(index,7).toString();
            fn_jTextField5.setText(Fn);
            ln_jTextField7.setText(LN);
            et_jTextField11.setText(ET);
            ad_jTextField10.setText(AD);
            pn_jTextField8.setText(phn);
            sal_jTextField12.setText(sal);
            
            
            
        }
        else if( upck == 1 )
        {
            upck = 0;
            System.out.println("update hbe ekhon");
            String Fn1 =fn_jTextField5.getText();
            String LN1 =ln_jTextField7.getText();
            String ET1 =et_jTextField11.getText();
            String AD1 =ad_jTextField10.getText();
            String phn1 =pn_jTextField8.getText();
            String sal1 =sal_jTextField12.getText();
            System.out.println(ID);
            
            if( new employee_update().update( ID,Fn1, LN1, ET1, AD1, phn1, sal1,stat ))
            {
                JOptionPane.showMessageDialog(null,"UPDATED !! ");
                retreve();
                fn_jTextField5.setText("");
                ln_jTextField7.setText("");
                et_jTextField11.setText("");
                ad_jTextField10.setText("");
                pn_jTextField8.setText("");
                sal_jTextField12.setText("");
            }
            else 
            {
                JOptionPane.showMessageDialog(null,"NOT UPDATED !! ");
            }
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        new admin().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Employee1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Employee1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Employee1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Employee1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Employee1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ad_jTextField10;
    private javax.swing.JTextField et_jTextField11;
    private javax.swing.JTextField fn_jTextField5;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField ln_jTextField7;
    private javax.swing.JTextField pn_jTextField8;
    private javax.swing.JTextField sal_jTextField12;
    // End of variables declaration//GEN-END:variables
}
