/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotelmanagement;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import static hotelmanagement.HotelManagement.total_cost;
import static hotelmanagement.customer_update.CONN_STRING;
import static hotelmanagement.customer_update.PASSWORD;
import static hotelmanagement.customer_update.USERNAME;
import java.sql.DriverManager;
import java.sql.ResultSet;

/**
 *
 * @author swapnil
 */
public class Event extends javax.swing.JFrame {
    
    int a1 = 0, a2 = 0,a3 = 0, a4 = 0, a5 = 0;

    /**
     * Creates new form Event
     */
    public Event() {
        initComponents();
        retreve();
    }
    void retreve()
    {
        String sql = "SELECT * FROM customer";
        try{
           
            Connection con= (Connection) DriverManager.getConnection(CONN_STRING, USERNAME, PASSWORD);
            
            Statement s =(Statement) con.prepareStatement(sql);
            
            ResultSet rs=s.executeQuery(sql);
            
            
            while(rs.next()){
                a1++;
              
            }
            
            
        }catch( Exception e ){
            System.out.println("problemmm");
            e.printStackTrace();
            
        }
        jLabel7.setText(a1+"");
        String sql1 = "SELECT * FROM employee_list";
        try{
           
            Connection con= (Connection) DriverManager.getConnection(CONN_STRING, USERNAME, PASSWORD);
            
            Statement s =(Statement) con.prepareStatement(sql1);
            
            ResultSet rs=s.executeQuery(sql1);
            
            
            while(rs.next()){
                String aaa = rs.getString(8);
                if( !aaa.equals("OFF DUTY"))
                {
                    a2++;
                }
              
            }
            
            
        }catch( Exception e ){
            System.out.println("problemmm");
            e.printStackTrace();
            
        }
        
        
        
        jLabel8.setText(a2+"");
        
        String sql4 = "SELECT * FROM tourdetails";
        try{
           
            Connection con= (Connection) DriverManager.getConnection(CONN_STRING, USERNAME, PASSWORD);
            
            Statement s =(Statement) con.prepareStatement(sql4);
            
            ResultSet rs=s.executeQuery(sql4);
            
            
            while(rs.next()){
                a4++;
              
            }
            
            
        }catch( Exception e ){
            System.out.println("problemmm");
            e.printStackTrace();
            
        }
        jLabel10.setText(a4+"");
        
        String sql5 = "SELECT * FROM meetings";
        try{
           
            Connection con= (Connection) DriverManager.getConnection(CONN_STRING, USERNAME, PASSWORD);
            
            Statement s =(Statement) con.prepareStatement(sql5);
            
            ResultSet rs=s.executeQuery(sql5);
            
            
            while(rs.next()){
                String aaa = rs.getString(6);
                if( !aaa.equals("vacant"))
                {
                    a5++;
                }
              
            }
            
            
        }catch( Exception e ){
            System.out.println("problemmm");
            e.printStackTrace();
            
        }
        
        jLabel11.setText(a5+"");
        jLabel9.setText(total_cost+"");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Number of Customer present in hotel: ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(110, 90, 280, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Number of employee working in hotel: ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(110, 140, 280, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Total cash");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(110, 180, 210, 17);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Tour");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(110, 220, 110, 17);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Meetings");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(110, 260, 160, 14);
        jPanel1.add(jLabel7);
        jLabel7.setBounds(400, 90, 150, 30);
        jPanel1.add(jLabel8);
        jLabel8.setBounds(390, 140, 180, 30);
        jPanel1.add(jLabel9);
        jLabel9.setBounds(400, 170, 160, 30);
        jPanel1.add(jLabel10);
        jLabel10.setBounds(400, 220, 170, 30);
        jPanel1.add(jLabel11);
        jLabel11.setBounds(390, 260, 170, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("EVENT");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(270, 20, 120, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotelmanagement/cover__WWW.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 750, 550);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 751, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Event.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Event.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Event.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Event.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Event().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
