/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotelmanagement;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import static hotelmanagement.sign_in.CONN_STRING;
import static hotelmanagement.sign_in.PASSWORD;
import static hotelmanagement.sign_in.USERNAME;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author swapnil
 */
public class ReservedRooms extends javax.swing.JFrame {
    public static final String USERNAME = "root";
    public static final String PASSWORD = "";
    public static final String CONN_STRING = "jdbc:mysql://localhost:3306/test";
    String a1, a2,a3,a4;

    /**
     * Creates new form ReservedRooms
     */
    public ReservedRooms() {
        initComponents();
        new Thread(){
            
            public void run(){
                while(true){
                    Date dNow = new Date( );
                    
                    SimpleDateFormat ft = new SimpleDateFormat ("E dd.MM.yyyy hh:mm:ss a");
                    String time = ""+ft.format(dNow);
                    
                    tt_jLabel3.setText(time);
                    
                }
            }
            
        }.start();
    }
    
    String a1rom()
    {
        return a1;
    }
    String a2rom()
    {
        return a2;
    }
    String a3rom()
    {
        return a3;
    }
    String a4rom()
    {
        return a4;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        Rooms_jComboBox5 = new javax.swing.JComboBox<>();
        AD_jComboBox3 = new javax.swing.JComboBox<>();
        CL_jComboBox4 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        tt_jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        NM_jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("BOOKED A ROOM !!");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(230, 0, 240, 40);
        jPanel1.add(jDateChooser1);
        jDateChooser1.setBounds(100, 100, 140, 30);
        jPanel1.add(jDateChooser2);
        jDateChooser2.setBounds(320, 100, 130, 30);

        Rooms_jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7" }));
        Rooms_jComboBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rooms_jComboBox5ActionPerformed(evt);
            }
        });
        jPanel1.add(Rooms_jComboBox5);
        Rooms_jComboBox5.setBounds(170, 230, 40, 20);

        AD_jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4" }));
        jPanel1.add(AD_jComboBox3);
        AD_jComboBox3.setBounds(310, 230, 40, 20);

        CL_jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4" }));
        CL_jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CL_jComboBox4ActionPerformed(evt);
            }
        });
        jPanel1.add(CL_jComboBox4);
        CL_jComboBox4.setBounds(420, 230, 40, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Rooms");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(170, 160, 60, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Adults");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(310, 160, 60, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Childrens");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(420, 160, 70, 30);

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton5.setText("FIND ROOMS");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(500, 90, 160, 50);
        jPanel1.add(tt_jLabel3);
        tt_jLabel3.setBounds(540, 20, 180, 20);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(10, 20, 90, 23);
        jPanel1.add(NM_jLabel3);
        NM_jLabel3.setBounds(150, 10, 100, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotelmanagement/cover__WWW.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 740, 360);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 661, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Rooms_jComboBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rooms_jComboBox5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Rooms_jComboBox5ActionPerformed

    private void CL_jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CL_jComboBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CL_jComboBox4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
         
        Date date1 =  jDateChooser1.getDate();
        String start = DateFormat.getDateInstance().format(date1);
        Date date2 =  jDateChooser2.getDate();
        String end = DateFormat.getDateInstance().format(date2);
        System.out.println( start + " " + end );
        
        FindRooms on = new FindRooms();
        on.premier_jButton1.setEnabled(false);
        on.Deluxe_jButton2.setEnabled(false);
        on.Exclusive_jButton4.setEnabled(false);
        on.Bangali_jButton5.setEnabled(false);
        boolean ok = false;
        
            String sql="SELECT * FROM  `rooms` WHERE  `Status` LIKE  '"+"vacant"+"' AND  `Ready` =  '"+"ok"+"'";
        
        try{
            
            Connection con= (Connection) DriverManager.getConnection(CONN_STRING, USERNAME, PASSWORD);
            
            Statement s =(Statement) con.prepareStatement(sql);
            
            ResultSet rs=s.executeQuery(sql);
            
            
            String D = "Deluxe";
            
            while(rs.next()){
                
                String TT = rs.getString(4);
                String cck = rs.getString(1);
                
                if( TT.equals("Premier") )
                {
                    //on.premier_jButton1.setEnabled(true);
                    ok = true;
                    a1= cck;
                    Guest_Info oo = new Guest_Info();
                   oo.rmmm_jLabel13.setText(a1);
                    
                }
                else if( TT.equals("Deluxe") )
                {
                    on.Deluxe_jButton2.setEnabled(true);
                    ok = true;
                   a2 = cck;
                   System.out.println(a2);
                   Guest_Info oo = new Guest_Info();
                   oo.rmmm_jLabel13.setText(a2);
                   
                }
                else if( TT.equals("Exclusive") )
                {
                    //on.Exclusive_jButton4.setEnabled(true);
                    ok = true;
                    a3 = cck;
                    Guest_Info oo = new Guest_Info();
                   oo.rmmm_jLabel13.setText(a3);
                }
                else if( TT.equals("Bengali") )
                {
                    //on.Bangali_jButton5.setEnabled(true);
                    ok = true;
                    a4 = cck;
                    Guest_Info oo = new Guest_Info();
                   oo.rmmm_jLabel13.setText(a4);
                 
                }
                
            }

            if( ok )
            {
                FindRooms FF = new FindRooms( ); 
                String r1 = Rooms_jComboBox5.getSelectedItem()+"";
                FF.tr_jLabel32.setText(r1);
                String r2 = AD_jComboBox3.getSelectedItem()+"";
                int a = Integer.parseInt(r2);
                String r3 = CL_jComboBox4.getSelectedItem()+"";
                int b = Integer.parseInt(r3);
                int c = a + b ;
                String RR = c + "";
                FF.tp_jLabel34.setText(RR);
                
                FF.setVisible( true );
                setVisible( false );
            }
           
            
            
            
            
    }catch(Exception e ){
        e.printStackTrace();
    }
       /*  pore korbo ei part ta 
    if( !ok )
    {
        String sql1="SELECT * FROM  `rooms` WHERE  `Status` LIKE  '"+"vacant"+"' AND  `Ready` =  '"+"ok"+"'";

    }
        */
        
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if( NM_jLabel3.getText().equals("GUEST"))
        {
            Guest GG = new Guest();
            GG.setVisible(true);
            setVisible(false);
        }
        else if( NM_jLabel3.getText().equals("Admin"))
        {
            new customer1().setVisible(true);
            setVisible(false);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReservedRooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReservedRooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReservedRooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReservedRooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReservedRooms().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> AD_jComboBox3;
    public javax.swing.JComboBox<String> CL_jComboBox4;
    public javax.swing.JLabel NM_jLabel3;
    public javax.swing.JComboBox<String> Rooms_jComboBox5;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel tt_jLabel3;
    // End of variables declaration//GEN-END:variables
}
