/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotelmanagement;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author swapnil
 */
public class sign_in extends javax.swing.JFrame {
    
    public static final String USERNAME = "root";
    public static final String PASSWORD = "";
    public static final String CONN_STRING = "jdbc:mysql://localhost:3306/test";
    public static String CustomerID = ""; 

    /**
     * Creates new form sign_in
     */
    public sign_in() {
        initComponents();
    }
    String check;
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        choice_jComboBox1 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        UserName_jTextField1 = new javax.swing.JTextField();
        Password_jPasswordField1 = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jButton1.setText("Sign In");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(550, 270, 73, 23);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Type");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(420, 220, 60, 20);

        choice_jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administator", "Customer", "Guest" }));
        choice_jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choice_jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(choice_jComboBox1);
        choice_jComboBox1.setBounds(510, 220, 110, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Password");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(420, 140, 110, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("User Name");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(420, 70, 130, 30);

        UserName_jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserName_jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(UserName_jTextField1);
        UserName_jTextField1.setBounds(420, 100, 200, 30);
        jPanel1.add(Password_jPasswordField1);
        Password_jPasswordField1.setBounds(420, 170, 200, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotelmanagement/signno.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(390, 50, 290, 270);

        jLabel3.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 28)); // NOI18N
        jLabel3.setText("WELCOME TO HOTEL KATUS_KUTUS");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 0, 670, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotelmanagement/signin.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 720, 400);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 715, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void choice_jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choice_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_choice_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        check = choice_jComboBox1.getSelectedItem()+"";
        
        if( check.equalsIgnoreCase("Guest"))
        {
            Guest G_ob = new Guest();
            G_ob.setVisible(true);
            setVisible(false);
            
        }
        
        else if( check.equalsIgnoreCase("Customer"))
            
        {
            String sql="SELECT * FROM  `customer` WHERE  `FirstName` LIKE  '"+UserName_jTextField1.getText()+"' AND  `Password` =  '"+Password_jPasswordField1.getText()+"'";
            
            try
            {
                Connection con= (Connection) DriverManager.getConnection(CONN_STRING, USERNAME, PASSWORD);
            
                Statement s =(Statement) con.prepareStatement(sql);
            
                ResultSet rs=s.executeQuery(sql);
                
                if(rs.next()){
                    Customer CC = new Customer();
                    CC.setVisible(true);
                    setVisible(false);
                    CC.CuNm_jLabel15.setText(UserName_jTextField1.getText());
                    
                    CustomerID = UserName_jTextField1.getText();
                
                }
                else{
                
                    JOptionPane.showMessageDialog(null,"Wrong Username or Password", "Access Denied",JOptionPane.ERROR_MESSAGE);
                
                }
                
            }catch(Exception e ){
                e.printStackTrace();
            }

        }
        else if( check.equalsIgnoreCase("Administator"))
            
        {
            String sql="SELECT * FROM  `manager` WHERE  `First Name` LIKE  '"+UserName_jTextField1.getText()+"' AND  `Password` =  '"+Password_jPasswordField1.getText()+"'";
            
            try
            {
                Connection con= (Connection) DriverManager.getConnection(CONN_STRING, USERNAME, PASSWORD);
            
                Statement s =(Statement) con.prepareStatement(sql);
            
            
            
                ResultSet rs=s.executeQuery(sql);
                if(rs.next()){
                    admin ad = new admin();
                    ad.setVisible(true);
                    setVisible(false);
                
                }
                else{
                
                    JOptionPane.showMessageDialog(null,"Wrong Username or Password", "Access Denied",JOptionPane.ERROR_MESSAGE);
                
                }
                
            }catch(Exception e ){
                e.printStackTrace();
            }

        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void UserName_jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserName_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserName_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sign_in.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sign_in.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sign_in.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sign_in.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sign_in().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField Password_jPasswordField1;
    public javax.swing.JTextField UserName_jTextField1;
    private javax.swing.JComboBox<String> choice_jComboBox1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
