/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotelmanagement;

import java.text.DateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author swapnil
 */
public class Tour extends javax.swing.JFrame {

    /**
     * Creates new form Tour
     */
    public Tour() {
        initComponents();
         T1_jTextField1.setEnabled(false);
         T2_jTextField2.setEnabled(false);
         T3_jTextField3.setEnabled(false);
         T4_jTextField4.setEnabled(false);
         S1_jButton1.setEnabled(false);
         S2_jButton2.setEnabled(false);
         S3_jButton3.setEnabled(false);
         S4_jButton4.setEnabled(false);
         
        
    }
    
    public void check ( String pp )
    {
        System.out.println("asche1 ");
        Date date1 =  jDateChooser1.getDate();
        String start = DateFormat.getDateInstance().format(date1);
        String nm = CN_jLabel38.getText();
        System.out.println(start);
        System.out.println("asche2 ");
        if( new TOUR_UPDATE().add( nm, start, pp )){
            JOptionPane.showMessageDialog(null,"Thanks For Touring With Us !! ");
            
            
        }
        else{
            JOptionPane.showMessageDialog(null,"opsss SORRY !!");
        }
        System.out.println("asche2 ");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        C4_jComboBox4 = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        T4_jTextField4 = new javax.swing.JTextField();
        S4_jButton4 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        C2_jComboBox2 = new javax.swing.JComboBox<>();
        jLabel26 = new javax.swing.JLabel();
        T2_jTextField2 = new javax.swing.JTextField();
        S2_jButton2 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        C3_jComboBox3 = new javax.swing.JComboBox<>();
        jLabel34 = new javax.swing.JLabel();
        T3_jTextField3 = new javax.swing.JTextField();
        S3_jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel36 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        p1_jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        C1_jComboBox1 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        T1_jTextField1 = new javax.swing.JTextField();
        S1_jButton1 = new javax.swing.JButton();
        jLabel37 = new javax.swing.JLabel();
        CN_jLabel38 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.setText("TOUR !! ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(410, 0, 90, 30);

        jLabel35.setText("PACKAGES");
        jPanel1.add(jLabel35);
        jLabel35.setBounds(400, 40, 90, 30);
        jPanel1.add(jDateChooser1);
        jDateChooser1.setBounds(180, 70, 140, 40);

        jPanel3.setLayout(null);

        jLabel11.setText("Dhaka , Sylet , Madhavkunda , Dhaka");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(270, 0, 210, 30);

        jLabel12.setText("5 Days 6 Nights");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(20, 40, 90, 30);

        jLabel13.setText("Cost Per Person ");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(20, 60, 90, 30);

        jLabel14.setText("USD");
        jPanel3.add(jLabel14);
        jLabel14.setBounds(20, 100, 34, 14);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel15.setText("289.79");
        jPanel3.add(jLabel15);
        jLabel15.setBounds(60, 80, 90, 40);

        jLabel16.setText("Details");
        jPanel3.add(jLabel16);
        jLabel16.setBounds(40, 30, 50, 20);

        jLabel17.setText("Number of Persons");
        jPanel3.add(jLabel17);
        jLabel17.setBounds(200, 40, 110, 30);

        C4_jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        C4_jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C4_jComboBox4ActionPerformed(evt);
            }
        });
        jPanel3.add(C4_jComboBox4);
        C4_jComboBox4.setBounds(310, 50, 40, 20);

        jLabel18.setText("Total Cost");
        jPanel3.add(jLabel18);
        jLabel18.setBounds(380, 40, 70, 30);

        T4_jTextField4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel3.add(T4_jTextField4);
        T4_jTextField4.setBounds(440, 40, 140, 50);

        S4_jButton4.setText("SELECT");
        S4_jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                S4_jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(S4_jButton4);
        S4_jButton4.setBounds(600, 40, 100, 50);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(10, 570, 770, 130);

        jPanel4.setLayout(null);

        jLabel19.setText("Dhaka , Bhandorban, Khagrachori, Rangamati, Dhaka");
        jPanel4.add(jLabel19);
        jLabel19.setBounds(270, 0, 290, 30);

        jLabel20.setText("5 Days 6 Nights");
        jPanel4.add(jLabel20);
        jLabel20.setBounds(20, 40, 90, 30);

        jLabel21.setText("Cost Per Person ");
        jPanel4.add(jLabel21);
        jLabel21.setBounds(20, 60, 90, 30);

        jLabel22.setText("USD");
        jPanel4.add(jLabel22);
        jLabel22.setBounds(20, 100, 34, 14);

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel23.setText("319.79");
        jPanel4.add(jLabel23);
        jLabel23.setBounds(60, 80, 90, 40);

        jLabel24.setText("Details");
        jPanel4.add(jLabel24);
        jLabel24.setBounds(40, 30, 50, 20);

        jLabel25.setText("Number of Persons");
        jPanel4.add(jLabel25);
        jLabel25.setBounds(200, 40, 110, 30);

        C2_jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        C2_jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C2_jComboBox2ActionPerformed(evt);
            }
        });
        jPanel4.add(C2_jComboBox2);
        C2_jComboBox2.setBounds(310, 50, 40, 20);

        jLabel26.setText("Total Cost");
        jPanel4.add(jLabel26);
        jLabel26.setBounds(380, 40, 70, 30);

        T2_jTextField2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel4.add(T2_jTextField2);
        T2_jTextField2.setBounds(440, 40, 140, 50);

        S2_jButton2.setText("SELECT");
        S2_jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                S2_jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(S2_jButton2);
        S2_jButton2.setBounds(600, 40, 100, 50);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(10, 270, 770, 130);

        jPanel5.setLayout(null);

        jLabel27.setText("Dhaka , Sundaban,  Dhaka");
        jPanel5.add(jLabel27);
        jLabel27.setBounds(270, 0, 150, 30);

        jLabel28.setText("5 Days 6 Nights");
        jPanel5.add(jLabel28);
        jLabel28.setBounds(20, 40, 90, 30);

        jLabel29.setText("Cost Per Person ");
        jPanel5.add(jLabel29);
        jLabel29.setBounds(20, 60, 90, 30);

        jLabel30.setText("USD");
        jPanel5.add(jLabel30);
        jLabel30.setBounds(20, 100, 34, 14);

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel31.setText("349.79");
        jPanel5.add(jLabel31);
        jLabel31.setBounds(60, 80, 90, 40);

        jLabel32.setText("Details");
        jPanel5.add(jLabel32);
        jLabel32.setBounds(40, 30, 50, 20);

        jLabel33.setText("Number of Persons");
        jPanel5.add(jLabel33);
        jLabel33.setBounds(200, 40, 110, 30);

        C3_jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        C3_jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C3_jComboBox3ActionPerformed(evt);
            }
        });
        jPanel5.add(C3_jComboBox3);
        C3_jComboBox3.setBounds(310, 50, 40, 20);

        jLabel34.setText("Total Cost");
        jPanel5.add(jLabel34);
        jLabel34.setBounds(380, 40, 70, 30);

        T3_jTextField3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel5.add(T3_jTextField3);
        T3_jTextField3.setBounds(440, 40, 140, 50);

        S3_jButton3.setText("SELECT");
        S3_jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                S3_jButton3ActionPerformed(evt);
            }
        });
        jPanel5.add(S3_jButton3);
        S3_jButton3.setBounds(600, 40, 100, 50);

        jPanel1.add(jPanel5);
        jPanel5.setBounds(10, 420, 770, 130);

        jButton5.setText("BACK");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(10, 20, 73, 23);

        jLabel36.setText("Select Your Journey Date");
        jPanel1.add(jLabel36);
        jLabel36.setBounds(10, 70, 150, 30);

        jPanel2.setLayout(null);

        p1_jLabel3.setText("Dhaka ,Cox_Bazar, Saint Martin , Dhaka");
        jPanel2.add(p1_jLabel3);
        p1_jLabel3.setBounds(290, 0, 220, 30);

        jLabel4.setText("3 Days 4 Nights");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(20, 40, 90, 30);

        jLabel5.setText("Cost Per Person ");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(20, 60, 90, 30);

        jLabel6.setText("USD");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(20, 100, 34, 14);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("119.79");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(60, 80, 90, 40);

        jLabel8.setText("Details");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(40, 30, 50, 20);

        jLabel9.setText("Number of Persons");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(200, 40, 110, 30);

        C1_jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        C1_jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C1_jComboBox1ActionPerformed(evt);
            }
        });
        jPanel2.add(C1_jComboBox1);
        C1_jComboBox1.setBounds(310, 50, 40, 20);

        jLabel10.setText("Total Cost");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(380, 40, 70, 30);

        T1_jTextField1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel2.add(T1_jTextField1);
        T1_jTextField1.setBounds(440, 40, 140, 50);

        S1_jButton1.setText("SELECT");
        S1_jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                S1_jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(S1_jButton1);
        S1_jButton1.setBounds(600, 40, 100, 50);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 120, 770, 130);

        jLabel37.setText("Customer ID: ");
        jPanel1.add(jLabel37);
        jLabel37.setBounds(520, 30, 90, 20);
        jPanel1.add(CN_jLabel38);
        CN_jLabel38.setBounds(610, 20, 110, 30);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 870, 760);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 872, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 757, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Customer cs = new Customer();
        cs.setVisible( true );
        setVisible( false );
    }//GEN-LAST:event_jButton5ActionPerformed

    private void C1_jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C1_jComboBox1ActionPerformed
        // TODO add your handling code here:
        String gt =C1_jComboBox1.getSelectedItem()+"";
        double d1 = Integer.parseInt(gt);
        d1 = d1 * 119.79;
        
        T1_jTextField1.setText( d1 + "" );
        S1_jButton1.setEnabled(true);
        S2_jButton2.setEnabled(false);
        S3_jButton3.setEnabled(false);
        S4_jButton4.setEnabled(false);
        
    }//GEN-LAST:event_C1_jComboBox1ActionPerformed

    private void C2_jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C2_jComboBox2ActionPerformed
        // TODO add your handling code here:
        String gt =C2_jComboBox2.getSelectedItem()+"";
        double d1 = Integer.parseInt(gt);
        d1 = d1 * 319.79;
        
        T2_jTextField2.setText( d1 + "" );
        S2_jButton2.setEnabled(true);
        S1_jButton1.setEnabled(false);
        S3_jButton3.setEnabled(false);
        S4_jButton4.setEnabled(false);
    }//GEN-LAST:event_C2_jComboBox2ActionPerformed

    private void C3_jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C3_jComboBox3ActionPerformed
        // TODO add your handling code here:
        String gt =C3_jComboBox3.getSelectedItem()+"";
        double d1 = Integer.parseInt(gt);
        d1 = d1 * 349.79;
        
        T3_jTextField3.setText( d1 + "" );
        S3_jButton3.setEnabled(true);
        S2_jButton2.setEnabled(false);
        S1_jButton1.setEnabled(false);
        S4_jButton4.setEnabled(false);
    }//GEN-LAST:event_C3_jComboBox3ActionPerformed

    private void C4_jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C4_jComboBox4ActionPerformed
        // TODO add your handling code here:
        String gt =C4_jComboBox4.getSelectedItem()+"";
        double d1 = Integer.parseInt(gt);
        d1 = d1 * 289.79;
        
        T4_jTextField4.setText( d1 + "" );
        S4_jButton4.setEnabled(true);
        S3_jButton3.setEnabled(false);
        S2_jButton2.setEnabled(false);
        S1_jButton1.setEnabled(false);
    }//GEN-LAST:event_C4_jComboBox4ActionPerformed

    private void S1_jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_S1_jButton1ActionPerformed
        // TODO add your handling code here:
        System.out.println("asche ");
        check ( p1_jLabel3.getText() );
        PAY pp = new PAY();
        pp.setVisible(true);
        pp.SC_jLabel7.setText(T1_jTextField1.getText());
        setVisible( false );
        
        
    }//GEN-LAST:event_S1_jButton1ActionPerformed

    private void S2_jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_S2_jButton2ActionPerformed
        // TODO add your handling code here:
        PAY pp = new PAY();
        pp.setVisible(true);
        pp.SC_jLabel7.setText(T2_jTextField2.getText());
        setVisible( false );
    }//GEN-LAST:event_S2_jButton2ActionPerformed

    private void S3_jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_S3_jButton3ActionPerformed
        // TODO add your handling code here:
        PAY pp = new PAY();
        pp.setVisible(true);
        pp.SC_jLabel7.setText(T3_jTextField3.getText());
        setVisible( false );
    }//GEN-LAST:event_S3_jButton3ActionPerformed

    private void S4_jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_S4_jButton4ActionPerformed
        // TODO add your handling code here:
        PAY pp = new PAY();
        pp.setVisible(true);
        pp.SC_jLabel7.setText(T4_jTextField4.getText());
        setVisible( false );
        
    }//GEN-LAST:event_S4_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tour().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> C1_jComboBox1;
    private javax.swing.JComboBox<String> C2_jComboBox2;
    private javax.swing.JComboBox<String> C3_jComboBox3;
    private javax.swing.JComboBox<String> C4_jComboBox4;
    public javax.swing.JLabel CN_jLabel38;
    private javax.swing.JButton S1_jButton1;
    private javax.swing.JButton S2_jButton2;
    private javax.swing.JButton S3_jButton3;
    private javax.swing.JButton S4_jButton4;
    private javax.swing.JTextField T1_jTextField1;
    private javax.swing.JTextField T2_jTextField2;
    private javax.swing.JTextField T3_jTextField3;
    private javax.swing.JTextField T4_jTextField4;
    private javax.swing.JButton jButton5;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel p1_jLabel3;
    // End of variables declaration//GEN-END:variables
}
